### ISSUE TITLE
Size options

### ISSUE THREAD

**Issue by danielfriis** [heyvito/lucide-rails#14]
Thanks for putting this together!

I feel I should be able to set the size, e.g. like this: `<%= lucide_icon('plus', width: '10px') %>`

And it seems you've implemented this functionality, but it doesn't seem to work for me.

**Comment by Glazy** [comment]
Hey @danielfriis, I can confirm the following works for me:

```erb
<%= lucide_icon('plus', 'width' => '10px') %>
```

**Comment by danielfriis** [comment]
That format works — thanks!

**Comment by heyvito** [comment]
Hey folks! I just pushed a commit allowing the symbols to be used as keys. Let's make it a bit more ergonomic, since we already bundled `active-support` through `railties` anyway. :)

I'll cut a new version in a few minutes and push it to rubygems. Thanks!

**Comment by heyvito** [comment]
Pushed v0.3.0 to RubyGems. ✨

**Comment by danielfriis** [comment]
Nice! 🙏

**Comment by Glazy** [comment]
Amazing, thanks @heyvito - great to have access to the newest icons too! 🎉
